[package]
name = 'PerSecondV6'
version = '0.6.106'
upgrade_policy = "compatible"

[addresses]
publisher = "_"

[dev-addresses]
publisher = "0xC0FFEE"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'
